query getEntry($section: [String], $slug: [String], $id: [QueryArgument], $site: [String], $uri: [String]) {
  entry(section: $section, slug: $slug, id: $id, site: $site, uri: $uri) {
    id
    uri
    url
    slug
    level
    typeHandle
    dateUpdated
    postDate
    title
  }
}
