query($uri:String!, $site:String) {
  seomatic (uri: $uri, site: $site, asArray:true) {
      metaTitleContainer
      metaTagContainer
      metaLinkContainer
      metaScriptContainer
      metaJsonLdContainer
      metaSiteVarsContainer
  }
}